"""Deterministic, publication-ready SVG charts for Annostat reports."""

from __future__ import annotations

from collections.abc import Mapping, Sequence
from html import escape
from pathlib import Path
from statistics import mean, median

import matplotlib as mpl
from matplotlib.backends.backend_svg import FigureCanvasSVG
from matplotlib.figure import Figure
from matplotlib.ticker import MaxNLocator, PercentFormatter


_INK = "#17211B"
_MUTED = "#66756D"
_GRID = "#DCE6E0"
_PAPER = "#FFFFFF"
_GREEN = "#087F5B"
_BLUE = "#2563EB"
_ORANGE = "#C2410C"
_PURPLE = "#7C3AED"
_PALETTE = (_GREEN, _BLUE, _ORANGE, _PURPLE, "#BE123C", "#0369A1")

_STYLE: dict[str, object] = {
    "figure.facecolor": _PAPER,
    "axes.facecolor": _PAPER,
    "axes.edgecolor": _GRID,
    "axes.labelcolor": _INK,
    "axes.titlecolor": _INK,
    "axes.titlesize": 12,
    "axes.titleweight": "bold",
    "axes.spines.top": False,
    "axes.spines.right": False,
    "axes.grid": False,
    "font.family": "sans-serif",
    "font.sans-serif": ["DejaVu Sans", "Arial", "Liberation Sans", "sans-serif"],
    "font.size": 10,
    "text.color": _INK,
    "xtick.color": _MUTED,
    "ytick.color": _INK,
    "svg.fonttype": "none",
    "svg.hashsalt": "annostat",
}


def _short_label(value: object, maximum: int = 36) -> str:
    """Shorten a visible label while preserving compact identifiers."""

    label = str(value)
    return label if len(label) <= maximum else label[: maximum - 1] + "…"


def _new_figure(
    width: float,
    height: float,
    title: str,
    description: str,
) -> Figure:
    """Create a consistently styled figure with room for report metadata."""

    figure = Figure(figsize=(width, height), layout="constrained")
    FigureCanvasSVG(figure)
    figure.suptitle(
        title,
        x=0.01,
        y=0.995,
        ha="left",
        va="top",
        fontsize=17,
        fontweight="bold",
        color=_INK,
    )
    figure.text(
        0.01,
        0.955,
        description,
        ha="left",
        va="top",
        fontsize=9,
        color=_MUTED,
    )
    layout = figure.get_layout_engine()
    if layout is not None:
        layout.set(rect=(0.01, 0.04, 0.99, 0.91))
    return figure


def _save_svg(
    figure: Figure,
    path: Path,
    title: str,
    description: str,
) -> None:
    """Write deterministic SVG with direct accessibility metadata."""

    figure.text(
        0.99,
        0.012,
        "Generated by Annostat",
        ha="right",
        va="bottom",
        fontsize=7,
        color=_MUTED,
    )
    canvas = FigureCanvasSVG(figure)
    canvas.print_svg(
        str(path),
        metadata={
            "Title": title,
            "Description": description,
            "Creator": "Annostat",
            "Date": None,
        },
    )
    svg = path.read_text(encoding="utf-8")
    start = svg.index("<svg ")
    tag_end = svg.index(">", start) + 1
    accessibility = (
        f"\n <title>{escape(title)}</title>"
        f"\n <desc>{escape(description)}</desc>"
    )
    path.write_text(
        svg[:tag_end] + accessibility + svg[tag_end:],
        encoding="utf-8",
    )
    figure.clear()


def _style_axes(axis: object, *, grid_axis: str = "x") -> None:
    """Apply the shared restrained scientific-axis treatment."""

    axis.grid(
        axis=grid_axis,
        color=_GRID,
        linewidth=0.8,
        alpha=0.9,
        zorder=0,
    )
    axis.tick_params(length=0, pad=6)
    axis.set_axisbelow(True)


def write_bar_chart(
    path: Path,
    title: str,
    counts: Mapping[str, int],
    *,
    description: str = "Counts across annotated coding sequences",
    axis_label: str = "Count",
    sort_by_value: bool = True,
    percentage_total: int | None = None,
) -> None:
    """Write a readable horizontal SVG bar chart."""

    items = list(counts.items())
    if sort_by_value:
        items.sort(key=lambda item: (-item[1], item[0]))
    height = max(3.2, 1.8 + 0.42 * max(1, len(items)))

    with mpl.rc_context(_STYLE):
        figure = _new_figure(12, height, title, description)
        axis = figure.subplots()
        _style_axes(axis)

        if not items:
            axis.text(
                0.5,
                0.5,
                "No data available",
                transform=axis.transAxes,
                ha="center",
                va="center",
                color=_MUTED,
            )
            axis.set_axis_off()
            _save_svg(figure, path, title, description)
            return

        labels = [_short_label(label, 48) for label, _ in items]
        values = [value for _, value in items]
        positions = list(range(len(items)))
        bars = axis.barh(
            positions,
            values,
            color=_GREEN,
            edgecolor="white",
            linewidth=0.8,
            height=0.68,
            zorder=2,
        )
        axis.set_yticks(positions, labels)
        axis.invert_yaxis()
        axis.set_xlabel(axis_label)
        axis.xaxis.set_major_locator(MaxNLocator(nbins=6, integer=True))

        maximum = max(values, default=0)
        label_room = 0.34 if percentage_total else 0.18
        axis.set_xlim(0, max(1, maximum * (1 + label_room)))
        offset = max(0.02 * maximum, 0.08)
        for bar, value in zip(bars, values):
            value_label = f"{value:,}"
            if percentage_total:
                value_label += f" ({100 * value / percentage_total:.2f}%)"
            axis.text(
                value + offset,
                bar.get_y() + bar.get_height() / 2,
                value_label,
                va="center",
                ha="left",
                fontsize=9,
                fontweight="bold",
                color=_INK,
            )

        _save_svg(figure, path, title, description)


def write_histogram(
    path: Path,
    title: str,
    values: Sequence[int],
    bins: int = 20,
) -> None:
    """Write a CDS-length histogram with mean and median markers."""

    sorted_values = sorted(values)
    plotted_values = sorted_values
    outlier_count = 0
    cutoff = None
    if len(sorted_values) >= 100:
        cutoff = sorted_values[int(0.99 * (len(sorted_values) - 1))]
        outlier_count = sum(value > cutoff for value in sorted_values)
        if outlier_count:
            plotted_values = [value for value in sorted_values if value <= cutoff]
    description = f"Distribution across {len(values):,} coding sequences"
    if outlier_count and cutoff is not None:
        description += (
            f"; main view through the 99th percentile "
            f"({outlier_count:,} CDS above {cutoff:,} nt)"
        )
    with mpl.rc_context(_STYLE):
        figure = _new_figure(12, 6.5, title, description)
        axis = figure.subplots()
        _style_axes(axis, grid_axis="y")
        axis.set_xlabel("CDS length (nucleotides)")
        axis.set_ylabel("Number of CDS")
        axis.yaxis.set_major_locator(MaxNLocator(integer=True))

        if not values:
            axis.text(
                0.5,
                0.5,
                "No CDS lengths available",
                transform=axis.transAxes,
                ha="center",
                va="center",
                color=_MUTED,
            )
            _save_svg(figure, path, title, description)
            return

        minimum, maximum = min(plotted_values), max(plotted_values)
        span = max(1, maximum - minimum + 1)
        bin_width = max(1, (span + bins - 1) // bins)
        bin_count = max(1, (span + bin_width - 1) // bin_width)
        edges = [minimum + index * bin_width for index in range(bin_count + 1)]
        if edges[-1] <= maximum:
            edges.append(edges[-1] + bin_width)

        axis.hist(
            plotted_values,
            bins=edges,
            color=_BLUE,
            edgecolor="white",
            linewidth=0.8,
            alpha=0.9,
            zorder=2,
        )
        axis.set_xlim(edges[0], edges[-1])
        center_markers = (
            (median(values), "Median", _GREEN),
            (mean(values), "Mean", _ORANGE),
        )
        for value, label, color in center_markers:
            if value > edges[-1]:
                axis.plot(
                    [],
                    [],
                    color=color,
                    linewidth=2,
                    linestyle="--",
                    label=f"{label}: {value:,.0f} nt (outside view)",
                )
                continue
            axis.axvline(
                value,
                color=color,
                linewidth=2,
                linestyle="--",
                label=f"{label}: {value:,.0f} nt",
                zorder=3,
            )
        axis.legend(frameon=False, loc="upper right")

        _save_svg(figure, path, title, description)


def write_comparison_overview(
    path: Path,
    profiles: Sequence[Mapping[str, object]],
) -> None:
    """Write small-multiple dot plots for normalized comparison metrics."""

    metrics = (
        ("GC content", "gc_percent", "%"),
        ("Coding density", "coding_density_percent", "%"),
        ("COG coverage", "cog_coverage_percent", "%"),
        ("Hypothetical CDS", "hypothetical_percent", "%"),
        ("Gene names", "gene_name_percent", "%"),
        ("CDS density", "cds_per_mb", " / Mb"),
    )
    title = "Normalized annotation overview"
    description = "Comparable percentages and rates; each panel uses its own labelled scale"
    height = max(11.5, len(metrics) * (1.4 + 0.28 * max(1, len(profiles))))

    with mpl.rc_context(_STYLE):
        figure = _new_figure(12, height, title, description)
        figure.set_layout_engine(None)
        figure.subplots_adjust(left=0.20, right=0.96, bottom=0.05, top=0.90, hspace=0.90)
        axes = list(figure.subplots(len(metrics), 1))
        labels = [_short_label(profile["label"], 28) for profile in profiles]
        positions = list(range(len(profiles)))

        for metric_index, (axis, (label, key, suffix)) in enumerate(
            zip(axes, metrics)
        ):
            _style_axes(axis)
            available_values = [
                float(profile[key])
                for profile in profiles
                if key != "cog_coverage_percent"
                or profile.get("cog_data_available", True)
            ]
            maximum = max(available_values, default=1)
            scale_max = 100.0 if suffix == "%" else max(1.0, maximum * 1.12)
            axis.set_xlim(0, scale_max * 1.14)
            axis.set_yticks(positions, labels)
            axis.invert_yaxis()
            axis.set_title(label, loc="left", pad=7)
            if suffix == "%":
                axis.xaxis.set_major_formatter(PercentFormatter(xmax=100))
            axis.xaxis.set_major_locator(MaxNLocator(nbins=6))

            for profile_index, profile in enumerate(profiles):
                if (
                    key == "cog_coverage_percent"
                    and not profile.get("cog_data_available", True)
                ):
                    axis.text(
                        scale_max * 1.01,
                        profile_index,
                        "Not available",
                        va="center",
                        fontsize=8,
                        color=_MUTED,
                    )
                    continue
                value = float(profile[key])
                color = _PALETTE[profile_index % len(_PALETTE)]
                axis.scatter(
                    [value],
                    [profile_index],
                    s=55,
                    color=color,
                    edgecolor="white",
                    linewidth=0.8,
                    zorder=3,
                )
                axis.text(
                    value + scale_max * 0.018,
                    profile_index,
                    f"{value:.2f}{suffix}",
                    va="center",
                    fontsize=8,
                    color=color,
                )
            axis.set_ylim(len(profiles) - 0.5, -0.5)
            if metric_index != len(metrics) - 1:
                axis.set_xlabel("")

        _save_svg(figure, path, title, description)


def write_cog_comparison(
    path: Path,
    profiles: Sequence[Mapping[str, object]],
    category_names: Mapping[str, str],
) -> None:
    """Write a two-genome COG delta chart or a multi-genome heatmap."""

    categories = sorted(
        set().union(
            *(profile["cog_category_percentages"] for profile in profiles)
        )
    )
    with mpl.rc_context(_STYLE):
        if len(profiles) == 2:
            _write_cog_delta(path, profiles, categories, category_names)
        else:
            _write_cog_heatmap(path, profiles, categories, category_names)


def _write_cog_delta(
    path: Path,
    profiles: Sequence[Mapping[str, object]],
    categories: Sequence[str],
    category_names: Mapping[str, str],
) -> None:
    """Write percentage-point COG differences for exactly two genomes."""

    title = "COG functional-profile difference"
    description = (
        f"Percentage-point change from {profiles[0]['label']} to "
        f"{profiles[1]['label']}; multi-category proteins contribute to each category"
    )
    labels = [
        _short_label(
            f"{category} - {category_names.get(category, 'Unclassified')}",
            52,
        )
        for category in categories
    ]
    deltas = [
        float(profiles[1]["cog_category_percentages"].get(category, 0))
        - float(profiles[0]["cog_category_percentages"].get(category, 0))
        for category in categories
    ]
    height = max(4.0, 1.8 + 0.38 * max(1, len(categories)))
    figure = _new_figure(12, height, title, description)
    axis = figure.subplots()
    _style_axes(axis)
    positions = list(range(len(categories)))
    colors = [_GREEN if value >= 0 else _BLUE for value in deltas]
    bars = axis.barh(
        positions,
        deltas,
        color=colors,
        edgecolor="white",
        linewidth=0.8,
        height=0.68,
        zorder=2,
    )
    axis.set_yticks(positions, labels)
    axis.invert_yaxis()
    axis.set_xlabel("Difference (percentage points)")
    axis.axvline(0, color=_INK, linewidth=1.1, zorder=3)
    bound = max((abs(value) for value in deltas), default=1) or 1
    axis.set_xlim(-bound * 1.3, bound * 1.3)
    offset = bound * 0.025
    for bar, delta in zip(bars, deltas):
        axis.text(
            delta + (offset if delta >= 0 else -offset),
            bar.get_y() + bar.get_height() / 2,
            f"{delta:+.2f} pp",
            ha="left" if delta >= 0 else "right",
            va="center",
            fontsize=8,
            fontweight="bold",
        )

    _save_svg(figure, path, title, description)


def _write_cog_heatmap(
    path: Path,
    profiles: Sequence[Mapping[str, object]],
    categories: Sequence[str],
    category_names: Mapping[str, str],
) -> None:
    """Write a dataset-by-category COG percentage heatmap."""

    title = "COG functional-profile heatmap"
    description = "Percentage of observed COG category assignments in each dataset"
    labels = [
        _short_label(
            f"{category} - {category_names.get(category, 'Unclassified')}",
            52,
        )
        for category in categories
    ]
    profile_labels = [_short_label(profile["label"], 18) for profile in profiles]
    matrix = [
        [
            float(profile["cog_category_percentages"].get(category, 0))
            for profile in profiles
        ]
        for category in categories
    ]
    width = max(10.0, 5.5 + 1.05 * max(1, len(profiles)))
    height = max(4.5, 2.0 + 0.38 * max(1, len(categories)))
    figure = _new_figure(width, height, title, description)
    axis = figure.subplots()
    image = axis.imshow(matrix, cmap="viridis", aspect="auto", zorder=1)
    axis.set_xticks(range(len(profiles)), profile_labels, rotation=35, ha="right")
    axis.set_yticks(range(len(categories)), labels)
    axis.tick_params(length=0)
    colorbar = figure.colorbar(image, ax=axis, shrink=0.78, pad=0.02)
    colorbar.set_label("COG assignments (%)")

    maximum = max((value for row in matrix for value in row), default=1) or 1
    for category_index, row in enumerate(matrix):
        for profile_index, value in enumerate(row):
            axis.text(
                profile_index,
                category_index,
                f"{value:.2f}%",
                ha="center",
                va="center",
                fontsize=7,
                color="white" if value / maximum > 0.48 else _INK,
            )

    _save_svg(figure, path, title, description)
